--- 
collections:
  - src: https://github.com/ansible-collections/community.general
    name: community.general

  - src: https://github.com/ansible-collections/community.crypto
    name: community.crypto

  - src: https://github.com/ansible-collections/ansible.posix
    name: ansible.posix  
